server:
  port: 8080
spring:
  mail:
    host: a2plcpnl0125.prod.iad2.secureserver.net
    port: 465
    username: hello@bucketdev.site
    password: aqWR5czbMObE
    protocol: smtps
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: a2plcpnl0125.prod.iad2.secureserver.net
  application:
    name: betapp
  datasource:
    #url: jdbc:mysql://localhost:3306/betapp?useLegacyDatetimeCode=false&autoReconnect=true
    url: jdbc:mysql://bucketdev.site:3306/betapp-bucketdev?useLegacyDatetimeCode=false&autoReconnect=true
    #username: root
    username: betapp
    #password: root
    password: cwf9yddkti99
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: validate
